
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 27 16:43:43 BRST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_dado = 4;
  public static final int Else = 7;
  public static final int Then = 24;
  public static final int Numero = 32;
  public static final int Begin = 13;
  public static final int Divisao = 31;
  public static final int PontoVirgula = 22;
  public static final int Op_booleano = 17;
  public static final int ERROR = 12;
  public static final int Repeat = 26;
  public static final int Identificador = 23;
  public static final int Parenteses_f = 19;
  public static final int All = 25;
  public static final int Until = 27;
  public static final int Op_relacional = 16;
  public static final int Subtracao = 29;
  public static final int End = 14;
  public static final int Parenteses_a = 18;
  public static final int EOF = 0;
  public static final int Multiplicacao = 30;
  public static final int If = 6;
  public static final int error = 1;
  public static final int Linha = 2;
  public static final int Op_logico = 11;
  public static final int Do = 8;
  public static final int Soma = 28;
  public static final int Igual = 10;
  public static final int Cadeia = 5;
  public static final int Ponto = 21;
  public static final int While = 9;
  public static final int Program = 20;
  public static final int Virgula = 15;
  public static final int Barra = 3;
}

