
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 28 13:21:04 BRST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_dado = 4;
  public static final int Else = 7;
  public static final int Then = 25;
  public static final int Numero = 33;
  public static final int Begin = 13;
  public static final int Divisao = 32;
  public static final int PontoVirgula = 23;
  public static final int Op_booleano = 17;
  public static final int ERROR = 12;
  public static final int Repeat = 27;
  public static final int Identificador = 24;
  public static final int Parenteses_f = 20;
  public static final int All = 26;
  public static final int Until = 28;
  public static final int Op_relacional = 16;
  public static final int Subtracao = 30;
  public static final int End = 14;
  public static final int Parenteses_a = 19;
  public static final int EOF = 0;
  public static final int Multiplicacao = 31;
  public static final int If = 6;
  public static final int error = 1;
  public static final int Linha = 2;
  public static final int Op_logico = 11;
  public static final int Do = 8;
  public static final int Soma = 29;
  public static final int Igual = 10;
  public static final int Cadeia = 5;
  public static final int Ponto = 22;
  public static final int While = 9;
  public static final int Program = 21;
  public static final int Virgula = 15;
  public static final int Op_Aritmeticos = 18;
  public static final int Barra = 3;
}

